# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_collection_card', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u85cf\u4e66\u8bc1\u7f16\u53f7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u85cf\u4e66\u8bc1',
                'verbose_name_plural': '\u85cf\u4e66\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=15, verbose_name='\u4e66\u540d')),
                ('book_volume', models.IntegerField(default=1, verbose_name='\u7b2c\u51e0\u518c')),
                ('book_introduction', models.CharField(max_length=200, verbose_name='\u4e66\u4ecb\u7ecd')),
                ('book_page', models.IntegerField(default=30, verbose_name='\u603b\u9875\u6570')),
                ('book_actual_page', models.IntegerField(default=0, verbose_name='\u73b0\u6709\u9875\u6570')),
                ('collection', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u91cf')),
                ('collection_whether', models.CharField(default='\u6536\u85cf', max_length=20, verbose_name='\u662f\u5426\u6536\u85cf')),
                ('book_number', models.CharField(blank=True, default='ZC180599Y', max_length=15, null=True, verbose_name='\u4e66\u7c4d\u7f16\u53f7')),
                ('fav_point', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u91cf')),
                ('fav_whether', models.CharField(default='\u70b9\u8d5e', max_length=20, verbose_name='\u662f\u5426\u70b9\u8d5e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66',
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='PublicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_price', models.IntegerField(default=50, verbose_name='\u4f17\u7b79\u4ef7\u683c')),
                ('book_state', models.CharField(blank=True, choices=[('unfinished', '\u4f17\u7b79\u4e2d'), ('end', '\u4f17\u7b79\u7ed3\u675f')], default='unfinished', max_length=20, null=True, verbose_name='\u4f17\u7b79\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_cover.Books', verbose_name='\u4e66\u7c4d')),
            ],
            options={
                'verbose_name': '\u4f17\u7b79',
                'verbose_name_plural': '\u4f17\u7b79',
            },
        ),
    ]
