# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_cover', '0002_auto_20180529_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_number',
            field=models.CharField(blank=True, default='ZC180699Y', max_length=15, null=True, verbose_name='\u4e66\u7c4d\u7f16\u53f7'),
        ),
    ]
