# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180529_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=7, verbose_name='\u6027\u522b'),
        ),
    ]
