# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Integral_block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='integral_numbers',
            new_name='grade_classification',
        ),
    ]
