# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Integral_block', '0003_auto_20180529_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integral',
            name='integral_numbers',
            field=models.IntegerField(default=0, max_length=100000, verbose_name='\u603b\u79ef\u5206'),
        ),
    ]
