# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_edit', '0002_auto_20180529_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='userfavotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='con_edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_edit.EditAddDetails', verbose_name='\u8bf4\u8bf4'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='con_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='comment',
            name='con_edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_edit.EditAddDetails', verbose_name='\u8bf4\u8bf4'),
        ),
    ]
