# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_cover', '0002_auto_20180529_1645'),
        ('book_other', '0003_relationship_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_cover.Books', verbose_name='\u4e66\u7c4d'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='is_payment',
            field=models.CharField(choices=[('paid', '\u5df2\u4ed8\u6b3e'), ('unpaid', '\u672a\u4ed8\u6b3e')], default='unpaid', max_length=30, verbose_name='\u662f\u5426\u4ed8\u6b3e'),
        ),
    ]
