# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_other', '0004_auto_20180529_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedformat',
            name='increase_integral',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u79ef\u5206\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='fixedformat',
            name='jurisdiction_explain',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u6743\u9650\u8bf4\u660e'),
        ),
    ]
