# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('content', models.CharField(max_length=500, verbose_name='\u5185\u5bb9')),
                ('background_pic', models.ImageField(upload_to='background/%Y/%m', verbose_name='\u80cc\u666f\u56fe')),
                ('fav_point', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4f17\u7b79\u8be6\u60c5\u7f16\u8f91',
                'verbose_name_plural': '\u4f17\u7b79\u8be6\u60c5\u7f16\u8f91',
            },
        ),
        migrations.CreateModel(
            name='EditAddDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('content', models.CharField(max_length=500, verbose_name='\u5185\u5bb9')),
                ('background_pic', models.ImageField(upload_to='background/%Y/%m', verbose_name='\u80cc\u666f\u56fe')),
                ('fav_point', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u91cf')),
                ('fav_whether', models.CharField(default='\u70b9\u8d5e', max_length=20, verbose_name='\u662f\u5426\u70b9\u8d5e')),
                ('follow_whether', models.CharField(default='\u5173\u6ce8', max_length=20, verbose_name='\u662f\u5426\u5173\u6ce8')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7f16\u8f91\u4e0e\u8be6\u60c5',
                'verbose_name_plural': '\u7f16\u8f91\u4e0e\u8be6\u60c5',
            },
        ),
    ]
