# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_cover', '0002_auto_20180529_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editadddetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_cover.Books', verbose_name='\u4e66\u7c4d'),
        ),
    ]
